apiVersion: v1
kind: Service
metadata:
  name: sysutil-app
  labels:
    name: sysutil-service
    app: sysutil-app
spec:
  type: NodePort
  ports:
    - port: 5001
      targetport: 5001
      nodeport: 31000
  selector:
    name: sysutil-pod
    app: sysutil-app
